---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: go-build
    image: golang:alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - apk add -U --no-cache git
      - go build -o ./controller .

  - name: publish image
    image: plugins/docker
    settings:
      repo: bitsbeats/velero-pvc-watcher
      auto_tag: true
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
  
  - name: lint helm chart
    image: dtzar/helm-kubectl:2.14.1
    commands:
      - helm lint velero-pvc-watcher
