{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero-pvc-watcher.fullname" . }}
  labels:
{{ include "velero-pvc-watcher.labels" . | indent 4 }}
{{- end }}